name: build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          submodules: true

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          cd _themes/sumi
          npm ci

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ github.token }}
          PAGES_REPO_NWO: ${{ github.repository }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2

  deploy:

    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
